---

- name: Delete all related cloud resources
  hosts: localhost
  gather_facts: False
  tasks:
    - name: delete the worker node servers
      rax:
        name: wp-swarm-manager%d
        image: "Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)"
        flavor: general1-1
        group: wp-swarm-manager
        state: absent
        wait: yes

    - name: delete the manager node server
      rax:
        name: wp-swarm-worker%d
        image: "Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM)"
        flavor: general1-1
        group: wp-swarm-worker
        state: absent
        wait: yes

    - name: delete the cloud database instance
      rax_cdb:
        name: wp-db
        flavor: 1
        volume: 2
        cdb_type: MariaDB
        cdb_version: 10.1
        state: absent

    - name: delete the Cloud Load Balancer
      rax_clb:
        name: wp-lb
        port: 80
        protocol: HTTP
        type: PUBLIC
        state: absent

    - pause: seconds=15

    - name: remove the cloud network
      rax_network:
        label: wp-swarm
        state: absent
